// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByI5gasmd34EKo3Rz2E0OLDMOmvbIOqn0',
    appId: '1:1038672515920:web:a5767c226e2d29f6ced255',
    messagingSenderId: '1038672515920',
    projectId: 'cloudnotifications-233b8',
    authDomain: 'cloudnotifications-233b8.firebaseapp.com',
    databaseURL: 'https://cloudnotifications-233b8.firebaseio.com',
    storageBucket: 'cloudnotifications-233b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexTx-qZ6lG8jb3g9mLLJ6e9rzVh15GZc',
    appId: '1:1038672515920:android:242f46e5bae9308cced255',
    messagingSenderId: '1038672515920',
    projectId: 'cloudnotifications-233b8',
    databaseURL: 'https://cloudnotifications-233b8.firebaseio.com',
    storageBucket: 'cloudnotifications-233b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvjbmNQ8eeiGDCKAfIBOnzgjOgNxJhyzQ',
    appId: '1:1038672515920:ios:d63be663e98b2607ced255',
    messagingSenderId: '1038672515920',
    projectId: 'cloudnotifications-233b8',
    databaseURL: 'https://cloudnotifications-233b8.firebaseio.com',
    storageBucket: 'cloudnotifications-233b8.appspot.com',
    androidClientId: '1038672515920-4596civfasputagdret03j9h5v5vfnt4.apps.googleusercontent.com',
    iosClientId: '1038672515920-uobvnmh4gt2c7eni8kr8jokibm1nah58.apps.googleusercontent.com',
    iosBundleId: 'com.example.squipAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvjbmNQ8eeiGDCKAfIBOnzgjOgNxJhyzQ',
    appId: '1:1038672515920:ios:1152f9da5ab27aacced255',
    messagingSenderId: '1038672515920',
    projectId: 'cloudnotifications-233b8',
    databaseURL: 'https://cloudnotifications-233b8.firebaseio.com',
    storageBucket: 'cloudnotifications-233b8.appspot.com',
    androidClientId: '1038672515920-4596civfasputagdret03j9h5v5vfnt4.apps.googleusercontent.com',
    iosClientId: '1038672515920-101uhqgh0if2s14ucdi5eg4rsd6ol5bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.squipAssignment.RunnerTests',
  );
}
